[package]
name = "radomsko"
version = "0.1.0"
authors = ["j39m"]
edition = "2018"

[[bin]]
name = "radomsko"
path = "src/main.rs"

[dependencies]
home = "^0"
clap = "^3"
tempfile = "^3"
walkdir = "^2"
indoc = "^1"
colorful = "^0"
subprocess = "^0"
