[package]
name = "radomsko"
version = "0.1.0"
authors = ["j39m"]
edition = "2018"

[[bin]]
name = "radomsko"
path = "src/main.rs"

[dependencies]
home = "0.5.3"
clap = "2.33.3"
tempfile = "3.2.0"
walkdir = "2.3.1"
indoc = "1.0"
