[package]
name = "radomsko"
version = "0.1.0"
authors = ["j39m"]
edition = "2018"

[[bin]]
name = "radomsko"
path = "src/main.rs"

[dependencies]
clap = "^3"
colorful = "^0"
ctrlc = "^3"
home = "^0"
indoc = "^1"
subprocess = "^0"
tempfile = "^3"
walkdir = "^2"
